baseURL = "https://bmuschko.com/"
languageCode = "en-us"
title = "Benjamin Muschko's development blog"
disqusShortname = "bmuschko-com"
googleAnalytics = "G-NQWC4QFM1D"

[params]
  avatar = "profile.jpg"
  author = "Benjamin Muschko"

[params.social]
  Github        = "bmuschko"
  Twitter       = "bmuschko"
  LinkedIn      = "benjaminmuschko"
  Stackoverflow = "users/528428/benjamin-muschko"
  Email         = "benjamin.muschko@gmail.com"

[[menu.main]]
  name = "blog"
  url = "/blog/"
[[menu.main]]
  name = "talks"
  url = "/talks/"